"""Server defaults for every NOT NULL column that had only a Python default.

Revision ID: 0006
Revises: 0005
Created: 2026-08-22

A `default=` on a SQLAlchemy column is applied by *SQLAlchemy*. Any other
writer — a raw `INSERT`, a loader, psql — inserts NULL and hits the NOT NULL
constraint. The indexing service writes raw SQL for throughput, and each
missing default surfaced one at a time as a `NotNullViolation` on a different
column: `extras`, then `authority`, then `quarantined`.

Fixing them at the call site would have fixed that one writer. Putting the
default in the database fixes every writer, including the next one.

Generated by walking the ORM metadata for columns that are NOT NULL, carry a
Python-side default and lack a server default.
"""

from __future__ import annotations

import pathlib

from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None

SQL = pathlib.Path(__file__).resolve().parents[1] / "sql" / "0006_server_defaults.sql"


def upgrade() -> None:
    op.execute(SQL.read_text())


def downgrade() -> None:
    # Dropping the defaults would reintroduce the failure this fixes, and the
    # values themselves are harmless. Deliberately a no-op.
    pass
