"""Server-side generation for UUID primary keys.

Revision ID: 0007
Revises: 0006
Created: 2026-08-22

The last member of the same family as 0006. Primary keys were generated by a
Python `default=uuid4`, so an `INSERT` written anywhere but through the ORM
inserted NULL.

`gen_random_uuid()` comes from pgcrypto, which revision 0001 installs into the
`extensions` schema — and which is on the search_path pinned by
`db/schema.py`, so the default resolves for every connection the application
opens.
"""

from __future__ import annotations

import pathlib

from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None

SQL = pathlib.Path(__file__).resolve().parents[1] / "sql" / "0007_uuid_defaults.sql"


def upgrade() -> None:
    op.execute(SQL.read_text())


def downgrade() -> None:
    pass
