-- The shape of an askcontent tenant database.
--
-- Generated by tools/dump_sql.py from a migrated database, not from
-- the ORM: this is what the migrations actually produced, and where
-- that differs from what the models say, this is the one answering
-- queries.
--
-- Load first, then sql/data.sql.

--
-- PostgreSQL database dump
--

\restrict iP4Z16zN1ABAY3bYYZinhgMoTsr0Sntbxil1eJd0HPHigHAjBh2bBG6NIGIUS3H

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: askcontent; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA askcontent;


--
-- Name: current_org(); Type: FUNCTION; Schema: askcontent; Owner: -
--

CREATE FUNCTION askcontent.current_org() RETURNS uuid
    LANGUAGE sql STABLE
    AS $$
  SELECT nullif(current_setting('askcontent.org_id', true), '')::uuid;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: askcontent_alembic_version; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: askcontent_answer_feedback; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_answer_feedback (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid,
    thread_id uuid,
    turn_id uuid,
    question text NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    citations jsonb DEFAULT '[]'::jsonb NOT NULL,
    verdict character varying(16) NOT NULL,
    reason character varying(32),
    comment text,
    promoted_case_id uuid,
    actor character varying(200),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_answer_feedback FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_app_user; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_app_user (
    email character varying(320) NOT NULL,
    display_name character varying(200),
    password_hash text,
    is_active boolean DEFAULT true NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: askcontent_auth_session; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_auth_session (
    token_hash character varying(128) NOT NULL,
    user_id uuid NOT NULL,
    org_id uuid,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: askcontent_authority_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_authority_rule (
    connector_id uuid NOT NULL,
    ordinal integer DEFAULT 0 NOT NULL,
    space character varying(200),
    path_prefix text,
    label character varying(200),
    tier character varying(16) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_authority_rule FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_chat_thread; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_chat_thread (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid,
    title character varying(300),
    role character varying(120),
    created_by character varying(200),
    archived_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    research jsonb
);

ALTER TABLE ONLY askcontent.askcontent_chat_thread FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_chat_turn; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_chat_turn (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    thread_id uuid NOT NULL,
    ordinal integer NOT NULL,
    question text NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    steps jsonb DEFAULT '[]'::jsonb NOT NULL,
    grounded boolean DEFAULT false NOT NULL,
    unsupported_reason text,
    answered_by jsonb DEFAULT '{}'::jsonb NOT NULL,
    elapsed_ms integer,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_chat_turn FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_collection; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_collection (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(300) NOT NULL,
    description text,
    business_group character varying(200),
    state character varying(16) DEFAULT 'draft'::character varying NOT NULL,
    auto_accept_enumerable boolean DEFAULT true NOT NULL,
    materialised_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_collection FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_collection_member; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_collection_member (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    kb_id character varying(200),
    title text,
    url text,
    contributed_by text[] DEFAULT '{}'::text[] NOT NULL,
    resolved_via character varying(16),
    resolve_score double precision,
    state character varying(16) DEFAULT 'member'::character varying NOT NULL,
    pinned character varying(8),
    pinned_by character varying(320),
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    missing_since timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    description text,
    space character varying(200),
    path text,
    doc_type character varying(32),
    owner character varying(320),
    source_created_at timestamp with time zone,
    source_updated_at timestamp with time zone,
    created_source character varying(16) DEFAULT 'none'::character varying NOT NULL,
    updated_source character varying(16) DEFAULT 'none'::character varying NOT NULL,
    date_evidence text,
    content_hash character varying(64),
    last_checked_at timestamp with time zone,
    last_changed_at timestamp with time zone,
    structure_hash character varying(64),
    last_verdict character varying(16),
    last_similarity double precision
);

ALTER TABLE ONLY askcontent.askcontent_collection_member FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_collection_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_collection_rule (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid NOT NULL,
    ordinal integer DEFAULT 0 NOT NULL,
    kind character varying(32) NOT NULL,
    effect character varying(8) DEFAULT 'include'::character varying NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    enumerable boolean DEFAULT true NOT NULL,
    last_run_at timestamp with time zone,
    last_candidate_count integer,
    capped boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_collection_rule FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_connector; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_connector (
    slug character varying(64) NOT NULL,
    name character varying(300) NOT NULL,
    workspace_id uuid NOT NULL,
    knowledgebase_id uuid NOT NULL,
    state character varying(16) DEFAULT 'draft'::character varying NOT NULL,
    scope jsonb NOT NULL,
    scope_hash character varying(64) NOT NULL,
    sensitivity_ceiling character varying(16) DEFAULT 'internal'::character varying NOT NULL,
    access_groups text[] DEFAULT '{}'::text[] NOT NULL,
    declared_access_class character varying(200),
    retrieval_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    catalog_version integer DEFAULT 1 NOT NULL,
    policy_version integer DEFAULT 1 NOT NULL,
    credential_ciphertext bytea,
    credential_key_id character varying(64),
    last_ingest_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    collection_id uuid,
    description text DEFAULT ''::text NOT NULL,
    system_instructions text DEFAULT ''::text NOT NULL,
    context_source jsonb,
    answer_model text,
    answer_tone text DEFAULT ''::text NOT NULL,
    reranker text,
    rerank_model text,
    research jsonb,
    CONSTRAINT ck_askcontent_connector_state CHECK (((state)::text = ANY ((ARRAY['draft'::character varying, 'active'::character varying, 'suspended'::character varying])::text[])))
);

ALTER TABLE ONLY askcontent.askcontent_connector FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_document; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_document (
    connector_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    title text NOT NULL,
    url text NOT NULL,
    path text,
    space character varying(200),
    owner character varying(320),
    labels text[] DEFAULT '{}'::text[] NOT NULL,
    source_version character varying(200),
    source_updated_at timestamp with time zone,
    sensitivity character varying(16) DEFAULT 'internal'::character varying NOT NULL,
    acl_principals text[] DEFAULT '{}'::text[] NOT NULL,
    extras jsonb DEFAULT '{}'::jsonb NOT NULL,
    mime character varying(128),
    size_bytes bigint,
    file_hash character varying(64),
    text_hash character varying(64),
    parser_id character varying(64),
    parser_version character varying(32),
    parse_path character varying(32),
    parse_quality jsonb DEFAULT '{}'::jsonb NOT NULL,
    refusal_reason text,
    doc_type character varying(32),
    doc_type_confidence double precision,
    doc_type_source character varying(16),
    doc_type_evidence text[] DEFAULT '{}'::text[] NOT NULL,
    authority character varying(16) DEFAULT 'supporting'::character varying NOT NULL,
    authority_reason character varying(64),
    staleness character varying(16) DEFAULT 'unknown_age'::character varying NOT NULL,
    in_scope boolean DEFAULT true NOT NULL,
    exclusion_rule character varying(64),
    exclusion_detail text,
    quarantined boolean DEFAULT false NOT NULL,
    superseded_by character varying(300),
    canonical_doc_id character varying(300),
    missing_since timestamp with time zone,
    last_seen_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    content_hash character varying(64),
    structure_hash character varying(64),
    last_content_change_at timestamp with time zone,
    last_cosmetic_change_at timestamp with time zone
);

ALTER TABLE ONLY askcontent.askcontent_document FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_document_chunk; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_document_chunk (
    connector_id uuid NOT NULL,
    document_id uuid NOT NULL,
    chunk_id character varying(64) NOT NULL,
    ordinal integer NOT NULL,
    text text NOT NULL,
    heading_path text[] DEFAULT '{}'::text[] NOT NULL,
    parent_text text,
    page integer,
    is_table boolean DEFAULT false NOT NULL,
    token_estimate integer,
    chunker_version character varying(32) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_code boolean DEFAULT false NOT NULL,
    overlap text DEFAULT ''::text NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_document_chunk FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_document_pin; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_document_pin (
    connector_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    field character varying(32) NOT NULL,
    value text NOT NULL,
    actor character varying(320) NOT NULL,
    note text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_document_pin FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_embed; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_embed (
    connector_id uuid NOT NULL,
    name character varying(200) NOT NULL,
    publishable_key character varying(128) NOT NULL,
    allowed_origins text[] DEFAULT '{}'::text[] NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    appearance jsonb DEFAULT '{}'::jsonb NOT NULL,
    session_count integer DEFAULT 0 NOT NULL,
    last_used_at timestamp with time zone
);

ALTER TABLE ONLY askcontent.askcontent_embed FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_embed_session; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_embed_session (
    embed_id uuid NOT NULL,
    visitor_id character varying(320) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_embed_session FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_embedding; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_embedding (
    connector_id uuid NOT NULL,
    kind character varying(24) NOT NULL,
    ref_id character varying(300) NOT NULL,
    parent_ref character varying(300),
    content_hash character varying(64) NOT NULL,
    model_id character varying(200) NOT NULL,
    dimension integer NOT NULL,
    vector extensions.vector(1536) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_embedding FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_eval_case; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_eval_case (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid NOT NULL,
    question text NOT NULL,
    expectations jsonb DEFAULT '[]'::jsonb NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    origin character varying(16) DEFAULT 'authored'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    role character varying(120),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_eval_case FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_eval_result; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_eval_result (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    run_id uuid NOT NULL,
    case_id uuid,
    question text NOT NULL,
    passed boolean NOT NULL,
    failures jsonb DEFAULT '[]'::jsonb NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    cited jsonb DEFAULT '[]'::jsonb NOT NULL,
    grounded boolean DEFAULT false NOT NULL,
    elapsed_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_eval_result FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_eval_run; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_eval_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    total integer DEFAULT 0 NOT NULL,
    passed integer DEFAULT 0 NOT NULL,
    failed integer DEFAULT 0 NOT NULL,
    context jsonb DEFAULT '{}'::jsonb NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_eval_run FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_field_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_field_rule (
    connector_id uuid NOT NULL,
    target character varying(64) NOT NULL,
    source character varying(200),
    coercion character varying(32) DEFAULT 'string'::character varying NOT NULL,
    value_map jsonb DEFAULT '{}'::jsonb NOT NULL,
    default_value text,
    prefer character varying(8) DEFAULT 'ecm'::character varying NOT NULL,
    observed_coverage double precision,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_field_rule FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_glossary_term; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_glossary_term (
    connector_id uuid NOT NULL,
    term character varying(200) NOT NULL,
    definition text NOT NULL,
    aliases text[] DEFAULT '{}'::text[] NOT NULL,
    source character varying(32) DEFAULT 'human'::character varying NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    status character varying(16) DEFAULT 'confirmed'::character varying NOT NULL,
    method character varying(16) DEFAULT 'human'::character varying NOT NULL,
    confidence double precision,
    occurrences integer DEFAULT 0 NOT NULL,
    documents integer DEFAULT 0 NOT NULL,
    evidence text[] DEFAULT '{}'::text[] NOT NULL,
    reviewed_by character varying(320),
    reviewed_at timestamp with time zone
);

ALTER TABLE ONLY askcontent.askcontent_glossary_term FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_job; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_job (
    connector_id uuid,
    kind character varying(32) NOT NULL,
    status character varying(16) DEFAULT 'queued'::character varying NOT NULL,
    progress jsonb DEFAULT '{}'::jsonb NOT NULL,
    error text,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 3 NOT NULL,
    locked_at timestamp with time zone,
    locked_by character varying(120),
    run_after timestamp with time zone DEFAULT now() NOT NULL,
    collection_id uuid
);

ALTER TABLE ONLY askcontent.askcontent_job FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_knowledgebase; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_knowledgebase (
    kb_id character varying(200) NOT NULL,
    name character varying(300) NOT NULL,
    description text,
    document_count integer DEFAULT 0 NOT NULL,
    last_indexed_at timestamp with time zone,
    embedding_model character varying(200),
    embedding_dimension integer,
    exposes_acl boolean DEFAULT false NOT NULL,
    observed_fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_knowledgebase FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_membership; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_membership (
    user_id uuid NOT NULL,
    role character varying(32) DEFAULT 'member'::character varying NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_membership FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_message; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_message (
    thread_id uuid NOT NULL,
    role character varying(16) NOT NULL,
    text text DEFAULT ''::text NOT NULL,
    sidecar jsonb DEFAULT '{}'::jsonb NOT NULL,
    refused boolean DEFAULT false NOT NULL,
    refusal_reason text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_message FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_model_catalog; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_model_catalog (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    kind text DEFAULT 'answer'::text NOT NULL,
    vendor text NOT NULL,
    model_id text NOT NULL,
    name text NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    ordinal integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: askcontent_org; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_org (
    slug character varying(64) NOT NULL,
    name character varying(200) NOT NULL,
    status character varying(24) DEFAULT 'active'::character varying NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: askcontent_quarantine_item; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_quarantine_item (
    connector_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    matched_class character varying(64) NOT NULL,
    redacted_span text,
    status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
    reviewed_by character varying(320),
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_quarantine_item FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_rbac_label_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_rbac_label_rule (
    role_id uuid NOT NULL,
    space character varying(200),
    label character varying(200),
    effect character varying(8) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_rbac_label_rule FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_rbac_policy_version; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_rbac_policy_version (
    connector_id uuid NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    changed_by character varying(320),
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_rbac_policy_version FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_rbac_role; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_rbac_role (
    connector_id uuid NOT NULL,
    name character varying(120) NOT NULL,
    description text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_rbac_role FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_rbac_role_member; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_rbac_role_member (
    role_id uuid NOT NULL,
    principal character varying(320) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_rbac_role_member FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_retrieval_plan; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_retrieval_plan (
    connector_id uuid NOT NULL,
    question_hash character varying(64) NOT NULL,
    question text NOT NULL,
    plan_hash character varying(64) NOT NULL,
    spec jsonb NOT NULL,
    evidence_chunk_ids text[] DEFAULT '{}'::text[] NOT NULL,
    catalog_version integer NOT NULL,
    reranker_id character varying(64) NOT NULL,
    hit_count integer DEFAULT 0 NOT NULL,
    last_used_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_retrieval_plan FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_retrieval_run; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_retrieval_run (
    connector_id uuid NOT NULL,
    actor character varying(320) NOT NULL,
    question text NOT NULL,
    spec jsonb NOT NULL,
    plan_hash character varying(64) NOT NULL,
    returned_doc_ids text[] DEFAULT '{}'::text[] NOT NULL,
    refused_doc_ids text[] DEFAULT '{}'::text[] NOT NULL,
    stale_index_count integer DEFAULT 0 NOT NULL,
    forbidden_count integer DEFAULT 0 NOT NULL,
    degraded text[] DEFAULT '{}'::text[] NOT NULL,
    answered boolean DEFAULT false NOT NULL,
    refusal_reason text,
    duration_ms double precision,
    cache_hit_rate double precision,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_retrieval_run FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_scope_change; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_scope_change (
    connector_id uuid NOT NULL,
    actor character varying(320) NOT NULL,
    scope_before jsonb,
    scope_after jsonb NOT NULL,
    added integer DEFAULT 0 NOT NULL,
    removed integer DEFAULT 0 NOT NULL,
    unchanged integer DEFAULT 0 NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_scope_change FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_thread; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_thread (
    workspace_id uuid NOT NULL,
    connector_id uuid NOT NULL,
    user_id uuid,
    title text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_thread FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_upload; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_upload (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid,
    filename text NOT NULL,
    mime character varying(128) NOT NULL,
    size_bytes bigint NOT NULL,
    file_hash character varying(64) NOT NULL,
    text_hash character varying(64),
    parser_id character varying(64),
    parser_version character varying(32),
    parse_path character varying(32),
    parse_quality jsonb DEFAULT '{}'::jsonb NOT NULL,
    refusal_reason text,
    title text,
    blob bytea NOT NULL,
    accepted_reason character varying(32),
    accepted_by character varying(320),
    duplicate_of character varying(300),
    status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_upload FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_url_paste; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_url_paste (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid,
    url text NOT NULL,
    normalised text NOT NULL,
    outcome character varying(16) NOT NULL,
    matched_doc_id character varying(300),
    rung character varying(16),
    score double precision,
    detail text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_url_paste FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_workspace; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_workspace (
    slug character varying(64) NOT NULL,
    name character varying(200) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.askcontent_workspace FORCE ROW LEVEL SECURITY;


--
-- Name: askcontent_alembic_version askcontent_alembic_version_pkc; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_alembic_version
    ADD CONSTRAINT askcontent_alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: askcontent_answer_feedback askcontent_answer_feedback_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_answer_feedback
    ADD CONSTRAINT askcontent_answer_feedback_pkey PRIMARY KEY (id);


--
-- Name: askcontent_chat_thread askcontent_chat_thread_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_chat_thread
    ADD CONSTRAINT askcontent_chat_thread_pkey PRIMARY KEY (id);


--
-- Name: askcontent_chat_turn askcontent_chat_turn_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_chat_turn
    ADD CONSTRAINT askcontent_chat_turn_pkey PRIMARY KEY (id);


--
-- Name: askcontent_chat_turn askcontent_chat_turn_thread_id_ordinal_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_chat_turn
    ADD CONSTRAINT askcontent_chat_turn_thread_id_ordinal_key UNIQUE (thread_id, ordinal);


--
-- Name: askcontent_collection_member askcontent_collection_member_collection_id_doc_id_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection_member
    ADD CONSTRAINT askcontent_collection_member_collection_id_doc_id_key UNIQUE (collection_id, doc_id);


--
-- Name: askcontent_collection_member askcontent_collection_member_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection_member
    ADD CONSTRAINT askcontent_collection_member_pkey PRIMARY KEY (id);


--
-- Name: askcontent_collection askcontent_collection_org_id_slug_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection
    ADD CONSTRAINT askcontent_collection_org_id_slug_key UNIQUE (org_id, slug);


--
-- Name: askcontent_collection askcontent_collection_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection
    ADD CONSTRAINT askcontent_collection_pkey PRIMARY KEY (id);


--
-- Name: askcontent_collection_rule askcontent_collection_rule_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection_rule
    ADD CONSTRAINT askcontent_collection_rule_pkey PRIMARY KEY (id);


--
-- Name: askcontent_eval_case askcontent_eval_case_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_case
    ADD CONSTRAINT askcontent_eval_case_pkey PRIMARY KEY (id);


--
-- Name: askcontent_eval_result askcontent_eval_result_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_result
    ADD CONSTRAINT askcontent_eval_result_pkey PRIMARY KEY (id);


--
-- Name: askcontent_eval_run askcontent_eval_run_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_run
    ADD CONSTRAINT askcontent_eval_run_pkey PRIMARY KEY (id);


--
-- Name: askcontent_model_catalog askcontent_model_catalog_org_id_kind_vendor_model_id_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_model_catalog
    ADD CONSTRAINT askcontent_model_catalog_org_id_kind_vendor_model_id_key UNIQUE (org_id, kind, vendor, model_id);


--
-- Name: askcontent_model_catalog askcontent_model_catalog_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_model_catalog
    ADD CONSTRAINT askcontent_model_catalog_pkey PRIMARY KEY (id);


--
-- Name: askcontent_upload askcontent_upload_org_id_file_hash_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_upload
    ADD CONSTRAINT askcontent_upload_org_id_file_hash_key UNIQUE (org_id, file_hash);


--
-- Name: askcontent_upload askcontent_upload_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_upload
    ADD CONSTRAINT askcontent_upload_pkey PRIMARY KEY (id);


--
-- Name: askcontent_url_paste askcontent_url_paste_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_url_paste
    ADD CONSTRAINT askcontent_url_paste_pkey PRIMARY KEY (id);


--
-- Name: askcontent_app_user pk_askcontent_app_user; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_app_user
    ADD CONSTRAINT pk_askcontent_app_user PRIMARY KEY (id);


--
-- Name: askcontent_auth_session pk_askcontent_auth_session; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_auth_session
    ADD CONSTRAINT pk_askcontent_auth_session PRIMARY KEY (id);


--
-- Name: askcontent_authority_rule pk_askcontent_authority_rule; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_authority_rule
    ADD CONSTRAINT pk_askcontent_authority_rule PRIMARY KEY (id);


--
-- Name: askcontent_connector pk_askcontent_connector; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_connector
    ADD CONSTRAINT pk_askcontent_connector PRIMARY KEY (id);


--
-- Name: askcontent_document pk_askcontent_document; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document
    ADD CONSTRAINT pk_askcontent_document PRIMARY KEY (id);


--
-- Name: askcontent_document_chunk pk_askcontent_document_chunk; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_chunk
    ADD CONSTRAINT pk_askcontent_document_chunk PRIMARY KEY (id);


--
-- Name: askcontent_document_pin pk_askcontent_document_pin; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_pin
    ADD CONSTRAINT pk_askcontent_document_pin PRIMARY KEY (id);


--
-- Name: askcontent_embed pk_askcontent_embed; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embed
    ADD CONSTRAINT pk_askcontent_embed PRIMARY KEY (id);


--
-- Name: askcontent_embed_session pk_askcontent_embed_session; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embed_session
    ADD CONSTRAINT pk_askcontent_embed_session PRIMARY KEY (id);


--
-- Name: askcontent_embedding pk_askcontent_embedding; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embedding
    ADD CONSTRAINT pk_askcontent_embedding PRIMARY KEY (id);


--
-- Name: askcontent_field_rule pk_askcontent_field_rule; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_field_rule
    ADD CONSTRAINT pk_askcontent_field_rule PRIMARY KEY (id);


--
-- Name: askcontent_glossary_term pk_askcontent_glossary_term; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_glossary_term
    ADD CONSTRAINT pk_askcontent_glossary_term PRIMARY KEY (id);


--
-- Name: askcontent_job pk_askcontent_job; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_job
    ADD CONSTRAINT pk_askcontent_job PRIMARY KEY (id);


--
-- Name: askcontent_knowledgebase pk_askcontent_knowledgebase; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_knowledgebase
    ADD CONSTRAINT pk_askcontent_knowledgebase PRIMARY KEY (id);


--
-- Name: askcontent_membership pk_askcontent_membership; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_membership
    ADD CONSTRAINT pk_askcontent_membership PRIMARY KEY (id);


--
-- Name: askcontent_message pk_askcontent_message; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_message
    ADD CONSTRAINT pk_askcontent_message PRIMARY KEY (id);


--
-- Name: askcontent_org pk_askcontent_org; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_org
    ADD CONSTRAINT pk_askcontent_org PRIMARY KEY (id);


--
-- Name: askcontent_quarantine_item pk_askcontent_quarantine_item; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_quarantine_item
    ADD CONSTRAINT pk_askcontent_quarantine_item PRIMARY KEY (id);


--
-- Name: askcontent_rbac_label_rule pk_askcontent_rbac_label_rule; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_label_rule
    ADD CONSTRAINT pk_askcontent_rbac_label_rule PRIMARY KEY (id);


--
-- Name: askcontent_rbac_policy_version pk_askcontent_rbac_policy_version; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_policy_version
    ADD CONSTRAINT pk_askcontent_rbac_policy_version PRIMARY KEY (id);


--
-- Name: askcontent_rbac_role pk_askcontent_rbac_role; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role
    ADD CONSTRAINT pk_askcontent_rbac_role PRIMARY KEY (id);


--
-- Name: askcontent_rbac_role_member pk_askcontent_rbac_role_member; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role_member
    ADD CONSTRAINT pk_askcontent_rbac_role_member PRIMARY KEY (id);


--
-- Name: askcontent_retrieval_plan pk_askcontent_retrieval_plan; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_retrieval_plan
    ADD CONSTRAINT pk_askcontent_retrieval_plan PRIMARY KEY (id);


--
-- Name: askcontent_retrieval_run pk_askcontent_retrieval_run; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_retrieval_run
    ADD CONSTRAINT pk_askcontent_retrieval_run PRIMARY KEY (id);


--
-- Name: askcontent_scope_change pk_askcontent_scope_change; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_scope_change
    ADD CONSTRAINT pk_askcontent_scope_change PRIMARY KEY (id);


--
-- Name: askcontent_thread pk_askcontent_thread; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_thread
    ADD CONSTRAINT pk_askcontent_thread PRIMARY KEY (id);


--
-- Name: askcontent_workspace pk_askcontent_workspace; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_workspace
    ADD CONSTRAINT pk_askcontent_workspace PRIMARY KEY (id);


--
-- Name: askcontent_app_user uq_askcontent_app_user_email; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_app_user
    ADD CONSTRAINT uq_askcontent_app_user_email UNIQUE (email);


--
-- Name: askcontent_auth_session uq_askcontent_auth_session_token_hash; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_auth_session
    ADD CONSTRAINT uq_askcontent_auth_session_token_hash UNIQUE (token_hash);


--
-- Name: askcontent_connector uq_askcontent_connector_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_connector
    ADD CONSTRAINT uq_askcontent_connector_org_id UNIQUE (org_id, slug);


--
-- Name: askcontent_document_chunk uq_askcontent_document_chunk_document_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_chunk
    ADD CONSTRAINT uq_askcontent_document_chunk_document_id UNIQUE (document_id, ordinal);


--
-- Name: askcontent_document uq_askcontent_document_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document
    ADD CONSTRAINT uq_askcontent_document_connector_id UNIQUE (connector_id, doc_id);


--
-- Name: askcontent_document_pin uq_askcontent_document_pin_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_pin
    ADD CONSTRAINT uq_askcontent_document_pin_connector_id UNIQUE (connector_id, doc_id, field);


--
-- Name: askcontent_embed uq_askcontent_embed_publishable_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embed
    ADD CONSTRAINT uq_askcontent_embed_publishable_key UNIQUE (publishable_key);


--
-- Name: askcontent_embedding uq_askcontent_embedding_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embedding
    ADD CONSTRAINT uq_askcontent_embedding_connector_id UNIQUE (connector_id, kind, ref_id, model_id);


--
-- Name: askcontent_field_rule uq_askcontent_field_rule_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_field_rule
    ADD CONSTRAINT uq_askcontent_field_rule_connector_id UNIQUE (connector_id, target);


--
-- Name: askcontent_glossary_term uq_askcontent_glossary_term_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_glossary_term
    ADD CONSTRAINT uq_askcontent_glossary_term_connector_id UNIQUE (connector_id, term);


--
-- Name: askcontent_knowledgebase uq_askcontent_knowledgebase_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_knowledgebase
    ADD CONSTRAINT uq_askcontent_knowledgebase_org_id UNIQUE (org_id, kb_id);


--
-- Name: askcontent_membership uq_askcontent_membership_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_membership
    ADD CONSTRAINT uq_askcontent_membership_org_id UNIQUE (org_id, user_id);


--
-- Name: askcontent_org uq_askcontent_org_slug; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_org
    ADD CONSTRAINT uq_askcontent_org_slug UNIQUE (slug);


--
-- Name: askcontent_rbac_role uq_askcontent_rbac_role_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role
    ADD CONSTRAINT uq_askcontent_rbac_role_connector_id UNIQUE (connector_id, name);


--
-- Name: askcontent_rbac_role_member uq_askcontent_rbac_role_member_role_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role_member
    ADD CONSTRAINT uq_askcontent_rbac_role_member_role_id UNIQUE (role_id, principal);


--
-- Name: askcontent_retrieval_plan uq_askcontent_retrieval_plan_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_retrieval_plan
    ADD CONSTRAINT uq_askcontent_retrieval_plan_connector_id UNIQUE (connector_id, question_hash, catalog_version, reranker_id);


--
-- Name: askcontent_workspace uq_askcontent_workspace_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_workspace
    ADD CONSTRAINT uq_askcontent_workspace_org_id UNIQUE (org_id, slug);


--
-- Name: ix_askcontent_authority_rule_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_authority_rule_org_id ON askcontent.askcontent_authority_rule USING btree (org_id);


--
-- Name: ix_askcontent_chat_thread_recent; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_chat_thread_recent ON askcontent.askcontent_chat_thread USING btree (org_id, updated_at DESC) WHERE (archived_at IS NULL);


--
-- Name: ix_askcontent_chunk_chunk_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_chunk_chunk_id ON askcontent.askcontent_document_chunk USING btree (connector_id, chunk_id);


--
-- Name: ix_askcontent_chunk_fts; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_chunk_fts ON askcontent.askcontent_document_chunk USING gin (to_tsvector('english'::regconfig, text));


--
-- Name: ix_askcontent_connector_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_connector_org_id ON askcontent.askcontent_connector USING btree (org_id);


--
-- Name: ix_askcontent_document_chunk_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_chunk_org_id ON askcontent.askcontent_document_chunk USING btree (org_id);


--
-- Name: ix_askcontent_document_fts; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_fts ON askcontent.askcontent_document USING gin (to_tsvector('english'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(path, ''::text))));


--
-- Name: ix_askcontent_document_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_org_id ON askcontent.askcontent_document USING btree (org_id);


--
-- Name: ix_askcontent_document_pin_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_pin_org_id ON askcontent.askcontent_document_pin USING btree (org_id);


--
-- Name: ix_askcontent_document_scope; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_scope ON askcontent.askcontent_document USING btree (connector_id, in_scope);


--
-- Name: ix_askcontent_document_space; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_space ON askcontent.askcontent_document USING btree (connector_id, space);


--
-- Name: ix_askcontent_document_updated; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_updated ON askcontent.askcontent_document USING btree (connector_id, source_updated_at);


--
-- Name: ix_askcontent_embed_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embed_org_id ON askcontent.askcontent_embed USING btree (org_id);


--
-- Name: ix_askcontent_embed_session_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embed_session_org_id ON askcontent.askcontent_embed_session USING btree (org_id);


--
-- Name: ix_askcontent_embedding_lookup; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embedding_lookup ON askcontent.askcontent_embedding USING btree (connector_id, kind);


--
-- Name: ix_askcontent_embedding_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embedding_org_id ON askcontent.askcontent_embedding USING btree (org_id);


--
-- Name: ix_askcontent_embedding_vector_cosine; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embedding_vector_cosine ON askcontent.askcontent_embedding USING hnsw (vector extensions.vector_cosine_ops) WITH (m='16', ef_construction='64');


--
-- Name: ix_askcontent_eval_result_run; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_eval_result_run ON askcontent.askcontent_eval_result USING btree (run_id);


--
-- Name: ix_askcontent_feedback_open; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_feedback_open ON askcontent.askcontent_answer_feedback USING btree (connector_id, created_at DESC) WHERE (((verdict)::text = 'unhelpful'::text) AND (promoted_case_id IS NULL));


--
-- Name: ix_askcontent_field_rule_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_field_rule_org_id ON askcontent.askcontent_field_rule USING btree (org_id);


--
-- Name: ix_askcontent_glossary_status; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_glossary_status ON askcontent.askcontent_glossary_term USING btree (connector_id, status);


--
-- Name: ix_askcontent_glossary_term_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_glossary_term_org_id ON askcontent.askcontent_glossary_term USING btree (org_id);


--
-- Name: ix_askcontent_job_claimable; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_job_claimable ON askcontent.askcontent_job USING btree (status, run_after) WHERE ((status)::text = ANY ((ARRAY['queued'::character varying, 'retry'::character varying])::text[]));


--
-- Name: ix_askcontent_job_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_job_org_id ON askcontent.askcontent_job USING btree (org_id);


--
-- Name: ix_askcontent_job_queue; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_job_queue ON askcontent.askcontent_job USING btree (status, created_at);


--
-- Name: ix_askcontent_knowledgebase_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_knowledgebase_org_id ON askcontent.askcontent_knowledgebase USING btree (org_id);


--
-- Name: ix_askcontent_member_checked; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_member_checked ON askcontent.askcontent_collection_member USING btree (collection_id, last_checked_at NULLS FIRST);


--
-- Name: ix_askcontent_member_state; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_member_state ON askcontent.askcontent_collection_member USING btree (collection_id, state);


--
-- Name: ix_askcontent_membership_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_membership_org_id ON askcontent.askcontent_membership USING btree (org_id);


--
-- Name: ix_askcontent_message_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_message_org_id ON askcontent.askcontent_message USING btree (org_id);


--
-- Name: ix_askcontent_message_thread; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_message_thread ON askcontent.askcontent_message USING btree (thread_id, created_at);


--
-- Name: ix_askcontent_quarantine_item_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_quarantine_item_org_id ON askcontent.askcontent_quarantine_item USING btree (org_id);


--
-- Name: ix_askcontent_rbac_label_rule_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_label_rule_org_id ON askcontent.askcontent_rbac_label_rule USING btree (org_id);


--
-- Name: ix_askcontent_rbac_policy_version_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_policy_version_org_id ON askcontent.askcontent_rbac_policy_version USING btree (org_id);


--
-- Name: ix_askcontent_rbac_role_member_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_role_member_org_id ON askcontent.askcontent_rbac_role_member USING btree (org_id);


--
-- Name: ix_askcontent_rbac_role_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_role_org_id ON askcontent.askcontent_rbac_role USING btree (org_id);


--
-- Name: ix_askcontent_retrieval_plan_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_retrieval_plan_org_id ON askcontent.askcontent_retrieval_plan USING btree (org_id);


--
-- Name: ix_askcontent_retrieval_run_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_retrieval_run_org_id ON askcontent.askcontent_retrieval_run USING btree (org_id);


--
-- Name: ix_askcontent_run_connector_time; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_run_connector_time ON askcontent.askcontent_retrieval_run USING btree (connector_id, created_at);


--
-- Name: ix_askcontent_scope_change_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_scope_change_org_id ON askcontent.askcontent_scope_change USING btree (org_id);


--
-- Name: ix_askcontent_thread_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_thread_org_id ON askcontent.askcontent_thread USING btree (org_id);


--
-- Name: ix_askcontent_workspace_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_workspace_org_id ON askcontent.askcontent_workspace USING btree (org_id);


--
-- Name: askcontent_answer_feedback askcontent_answer_feedback_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_answer_feedback
    ADD CONSTRAINT askcontent_answer_feedback_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE SET NULL;


--
-- Name: askcontent_answer_feedback askcontent_answer_feedback_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_answer_feedback
    ADD CONSTRAINT askcontent_answer_feedback_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_answer_feedback askcontent_answer_feedback_thread_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_answer_feedback
    ADD CONSTRAINT askcontent_answer_feedback_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES askcontent.askcontent_chat_thread(id) ON DELETE SET NULL;


--
-- Name: askcontent_answer_feedback askcontent_answer_feedback_turn_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_answer_feedback
    ADD CONSTRAINT askcontent_answer_feedback_turn_id_fkey FOREIGN KEY (turn_id) REFERENCES askcontent.askcontent_chat_turn(id) ON DELETE SET NULL;


--
-- Name: askcontent_chat_thread askcontent_chat_thread_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_chat_thread
    ADD CONSTRAINT askcontent_chat_thread_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE SET NULL;


--
-- Name: askcontent_chat_thread askcontent_chat_thread_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_chat_thread
    ADD CONSTRAINT askcontent_chat_thread_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_chat_turn askcontent_chat_turn_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_chat_turn
    ADD CONSTRAINT askcontent_chat_turn_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_chat_turn askcontent_chat_turn_thread_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_chat_turn
    ADD CONSTRAINT askcontent_chat_turn_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES askcontent.askcontent_chat_thread(id) ON DELETE CASCADE;


--
-- Name: askcontent_collection_member askcontent_collection_member_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection_member
    ADD CONSTRAINT askcontent_collection_member_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.askcontent_collection(id) ON DELETE CASCADE;


--
-- Name: askcontent_collection_member askcontent_collection_member_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection_member
    ADD CONSTRAINT askcontent_collection_member_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_collection askcontent_collection_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection
    ADD CONSTRAINT askcontent_collection_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_collection_rule askcontent_collection_rule_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection_rule
    ADD CONSTRAINT askcontent_collection_rule_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.askcontent_collection(id) ON DELETE CASCADE;


--
-- Name: askcontent_collection_rule askcontent_collection_rule_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_collection_rule
    ADD CONSTRAINT askcontent_collection_rule_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_connector askcontent_connector_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_connector
    ADD CONSTRAINT askcontent_connector_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.askcontent_collection(id);


--
-- Name: askcontent_eval_case askcontent_eval_case_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_case
    ADD CONSTRAINT askcontent_eval_case_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_eval_case askcontent_eval_case_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_case
    ADD CONSTRAINT askcontent_eval_case_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_eval_result askcontent_eval_result_case_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_result
    ADD CONSTRAINT askcontent_eval_result_case_id_fkey FOREIGN KEY (case_id) REFERENCES askcontent.askcontent_eval_case(id) ON DELETE SET NULL;


--
-- Name: askcontent_eval_result askcontent_eval_result_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_result
    ADD CONSTRAINT askcontent_eval_result_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_eval_result askcontent_eval_result_run_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_result
    ADD CONSTRAINT askcontent_eval_result_run_id_fkey FOREIGN KEY (run_id) REFERENCES askcontent.askcontent_eval_run(id) ON DELETE CASCADE;


--
-- Name: askcontent_eval_run askcontent_eval_run_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_run
    ADD CONSTRAINT askcontent_eval_run_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_eval_run askcontent_eval_run_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_eval_run
    ADD CONSTRAINT askcontent_eval_run_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_job askcontent_job_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_job
    ADD CONSTRAINT askcontent_job_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.askcontent_collection(id) ON DELETE CASCADE;


--
-- Name: askcontent_upload askcontent_upload_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_upload
    ADD CONSTRAINT askcontent_upload_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.askcontent_collection(id) ON DELETE CASCADE;


--
-- Name: askcontent_upload askcontent_upload_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_upload
    ADD CONSTRAINT askcontent_upload_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_url_paste askcontent_url_paste_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_url_paste
    ADD CONSTRAINT askcontent_url_paste_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.askcontent_collection(id) ON DELETE CASCADE;


--
-- Name: askcontent_url_paste askcontent_url_paste_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_url_paste
    ADD CONSTRAINT askcontent_url_paste_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_auth_session fk_askcontent_auth_session_user_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_auth_session
    ADD CONSTRAINT fk_askcontent_auth_session_user_id FOREIGN KEY (user_id) REFERENCES askcontent.askcontent_app_user(id) ON DELETE CASCADE;


--
-- Name: askcontent_authority_rule fk_askcontent_authority_rule_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_authority_rule
    ADD CONSTRAINT fk_askcontent_authority_rule_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_authority_rule fk_askcontent_authority_rule_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_authority_rule
    ADD CONSTRAINT fk_askcontent_authority_rule_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_connector fk_askcontent_connector_knowledgebase_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_connector
    ADD CONSTRAINT fk_askcontent_connector_knowledgebase_id FOREIGN KEY (knowledgebase_id) REFERENCES askcontent.askcontent_knowledgebase(id) ON DELETE RESTRICT;


--
-- Name: askcontent_connector fk_askcontent_connector_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_connector
    ADD CONSTRAINT fk_askcontent_connector_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_connector fk_askcontent_connector_workspace_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_connector
    ADD CONSTRAINT fk_askcontent_connector_workspace_id FOREIGN KEY (workspace_id) REFERENCES askcontent.askcontent_workspace(id) ON DELETE CASCADE;


--
-- Name: askcontent_document_chunk fk_askcontent_document_chunk_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_chunk
    ADD CONSTRAINT fk_askcontent_document_chunk_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_document_chunk fk_askcontent_document_chunk_document_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_chunk
    ADD CONSTRAINT fk_askcontent_document_chunk_document_id FOREIGN KEY (document_id) REFERENCES askcontent.askcontent_document(id) ON DELETE CASCADE;


--
-- Name: askcontent_document_chunk fk_askcontent_document_chunk_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_chunk
    ADD CONSTRAINT fk_askcontent_document_chunk_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_document fk_askcontent_document_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document
    ADD CONSTRAINT fk_askcontent_document_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_document fk_askcontent_document_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document
    ADD CONSTRAINT fk_askcontent_document_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_document_pin fk_askcontent_document_pin_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_pin
    ADD CONSTRAINT fk_askcontent_document_pin_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_document_pin fk_askcontent_document_pin_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_document_pin
    ADD CONSTRAINT fk_askcontent_document_pin_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_embed fk_askcontent_embed_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embed
    ADD CONSTRAINT fk_askcontent_embed_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_embed fk_askcontent_embed_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embed
    ADD CONSTRAINT fk_askcontent_embed_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_embed_session fk_askcontent_embed_session_embed_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embed_session
    ADD CONSTRAINT fk_askcontent_embed_session_embed_id FOREIGN KEY (embed_id) REFERENCES askcontent.askcontent_embed(id) ON DELETE CASCADE;


--
-- Name: askcontent_embed_session fk_askcontent_embed_session_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embed_session
    ADD CONSTRAINT fk_askcontent_embed_session_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_embedding fk_askcontent_embedding_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embedding
    ADD CONSTRAINT fk_askcontent_embedding_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_embedding fk_askcontent_embedding_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_embedding
    ADD CONSTRAINT fk_askcontent_embedding_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_field_rule fk_askcontent_field_rule_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_field_rule
    ADD CONSTRAINT fk_askcontent_field_rule_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_field_rule fk_askcontent_field_rule_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_field_rule
    ADD CONSTRAINT fk_askcontent_field_rule_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_glossary_term fk_askcontent_glossary_term_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_glossary_term
    ADD CONSTRAINT fk_askcontent_glossary_term_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_glossary_term fk_askcontent_glossary_term_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_glossary_term
    ADD CONSTRAINT fk_askcontent_glossary_term_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_job fk_askcontent_job_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_job
    ADD CONSTRAINT fk_askcontent_job_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_job fk_askcontent_job_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_job
    ADD CONSTRAINT fk_askcontent_job_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_knowledgebase fk_askcontent_knowledgebase_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_knowledgebase
    ADD CONSTRAINT fk_askcontent_knowledgebase_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_membership fk_askcontent_membership_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_membership
    ADD CONSTRAINT fk_askcontent_membership_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_membership fk_askcontent_membership_user_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_membership
    ADD CONSTRAINT fk_askcontent_membership_user_id FOREIGN KEY (user_id) REFERENCES askcontent.askcontent_app_user(id) ON DELETE CASCADE;


--
-- Name: askcontent_message fk_askcontent_message_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_message
    ADD CONSTRAINT fk_askcontent_message_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_message fk_askcontent_message_thread_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_message
    ADD CONSTRAINT fk_askcontent_message_thread_id FOREIGN KEY (thread_id) REFERENCES askcontent.askcontent_thread(id) ON DELETE CASCADE;


--
-- Name: askcontent_quarantine_item fk_askcontent_quarantine_item_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_quarantine_item
    ADD CONSTRAINT fk_askcontent_quarantine_item_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_quarantine_item fk_askcontent_quarantine_item_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_quarantine_item
    ADD CONSTRAINT fk_askcontent_quarantine_item_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_label_rule fk_askcontent_rbac_label_rule_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_label_rule
    ADD CONSTRAINT fk_askcontent_rbac_label_rule_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_label_rule fk_askcontent_rbac_label_rule_role_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_label_rule
    ADD CONSTRAINT fk_askcontent_rbac_label_rule_role_id FOREIGN KEY (role_id) REFERENCES askcontent.askcontent_rbac_role(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_policy_version fk_askcontent_rbac_policy_version_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_policy_version
    ADD CONSTRAINT fk_askcontent_rbac_policy_version_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_policy_version fk_askcontent_rbac_policy_version_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_policy_version
    ADD CONSTRAINT fk_askcontent_rbac_policy_version_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_role fk_askcontent_rbac_role_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role
    ADD CONSTRAINT fk_askcontent_rbac_role_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_role_member fk_askcontent_rbac_role_member_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role_member
    ADD CONSTRAINT fk_askcontent_rbac_role_member_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_role_member fk_askcontent_rbac_role_member_role_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role_member
    ADD CONSTRAINT fk_askcontent_rbac_role_member_role_id FOREIGN KEY (role_id) REFERENCES askcontent.askcontent_rbac_role(id) ON DELETE CASCADE;


--
-- Name: askcontent_rbac_role fk_askcontent_rbac_role_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_rbac_role
    ADD CONSTRAINT fk_askcontent_rbac_role_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_retrieval_plan fk_askcontent_retrieval_plan_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_retrieval_plan
    ADD CONSTRAINT fk_askcontent_retrieval_plan_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_retrieval_plan fk_askcontent_retrieval_plan_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_retrieval_plan
    ADD CONSTRAINT fk_askcontent_retrieval_plan_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_retrieval_run fk_askcontent_retrieval_run_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_retrieval_run
    ADD CONSTRAINT fk_askcontent_retrieval_run_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_retrieval_run fk_askcontent_retrieval_run_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_retrieval_run
    ADD CONSTRAINT fk_askcontent_retrieval_run_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_scope_change fk_askcontent_scope_change_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_scope_change
    ADD CONSTRAINT fk_askcontent_scope_change_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_scope_change fk_askcontent_scope_change_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_scope_change
    ADD CONSTRAINT fk_askcontent_scope_change_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_thread fk_askcontent_thread_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_thread
    ADD CONSTRAINT fk_askcontent_thread_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.askcontent_connector(id) ON DELETE CASCADE;


--
-- Name: askcontent_thread fk_askcontent_thread_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_thread
    ADD CONSTRAINT fk_askcontent_thread_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_thread fk_askcontent_thread_user_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_thread
    ADD CONSTRAINT fk_askcontent_thread_user_id FOREIGN KEY (user_id) REFERENCES askcontent.askcontent_app_user(id) ON DELETE SET NULL;


--
-- Name: askcontent_thread fk_askcontent_thread_workspace_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_thread
    ADD CONSTRAINT fk_askcontent_thread_workspace_id FOREIGN KEY (workspace_id) REFERENCES askcontent.askcontent_workspace(id) ON DELETE CASCADE;


--
-- Name: askcontent_workspace fk_askcontent_workspace_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_workspace
    ADD CONSTRAINT fk_askcontent_workspace_org_id FOREIGN KEY (org_id) REFERENCES askcontent.askcontent_org(id) ON DELETE CASCADE;


--
-- Name: askcontent_answer_feedback answer_feedback_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY answer_feedback_tenant_isolation ON askcontent.askcontent_answer_feedback USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_answer_feedback; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_answer_feedback ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_authority_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_authority_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_chat_thread; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_chat_thread ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_chat_turn; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_chat_turn ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_collection; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_collection ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_collection_member; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_collection_member ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_collection_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_collection_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_connector; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_connector ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_document; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_document ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_document_chunk; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_document_chunk ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_document_pin; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_document_pin ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_embed; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_embed ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_embed_session; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_embed_session ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_embedding; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_embedding ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_eval_case; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_eval_case ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_eval_result; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_eval_result ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_eval_run; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_eval_run ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_field_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_field_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_glossary_term; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_glossary_term ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_job; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_job ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_knowledgebase; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_knowledgebase ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_membership; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_membership ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_message; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_message ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_quarantine_item; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_quarantine_item ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_rbac_label_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_rbac_label_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_rbac_policy_version; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_rbac_policy_version ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_rbac_role; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_rbac_role ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_rbac_role_member; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_rbac_role_member ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_retrieval_plan; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_retrieval_plan ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_retrieval_run; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_retrieval_run ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_scope_change; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_scope_change ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_thread; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_thread ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_upload; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_upload ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_url_paste; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_url_paste ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_workspace; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.askcontent_workspace ENABLE ROW LEVEL SECURITY;

--
-- Name: askcontent_authority_rule authority_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY authority_rule_tenant_isolation ON askcontent.askcontent_authority_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_chat_thread chat_thread_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY chat_thread_tenant_isolation ON askcontent.askcontent_chat_thread USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_chat_turn chat_turn_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY chat_turn_tenant_isolation ON askcontent.askcontent_chat_turn USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_collection_member collection_member_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY collection_member_tenant_isolation ON askcontent.askcontent_collection_member USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_collection_rule collection_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY collection_rule_tenant_isolation ON askcontent.askcontent_collection_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_collection collection_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY collection_tenant_isolation ON askcontent.askcontent_collection USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_connector connector_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY connector_tenant_isolation ON askcontent.askcontent_connector USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_document_chunk document_chunk_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY document_chunk_tenant_isolation ON askcontent.askcontent_document_chunk USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_document_pin document_pin_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY document_pin_tenant_isolation ON askcontent.askcontent_document_pin USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_document document_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY document_tenant_isolation ON askcontent.askcontent_document USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_embed_session embed_session_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY embed_session_tenant_isolation ON askcontent.askcontent_embed_session USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_embed embed_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY embed_tenant_isolation ON askcontent.askcontent_embed USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_embedding embedding_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY embedding_tenant_isolation ON askcontent.askcontent_embedding USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_eval_case eval_case_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY eval_case_tenant_isolation ON askcontent.askcontent_eval_case USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_eval_result eval_result_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY eval_result_tenant_isolation ON askcontent.askcontent_eval_result USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_eval_run eval_run_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY eval_run_tenant_isolation ON askcontent.askcontent_eval_run USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_field_rule field_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY field_rule_tenant_isolation ON askcontent.askcontent_field_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_glossary_term glossary_term_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY glossary_term_tenant_isolation ON askcontent.askcontent_glossary_term USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_job job_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY job_tenant_isolation ON askcontent.askcontent_job USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_knowledgebase knowledgebase_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY knowledgebase_tenant_isolation ON askcontent.askcontent_knowledgebase USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_membership membership_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY membership_tenant_isolation ON askcontent.askcontent_membership USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_message message_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY message_tenant_isolation ON askcontent.askcontent_message USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_quarantine_item quarantine_item_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY quarantine_item_tenant_isolation ON askcontent.askcontent_quarantine_item USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_rbac_label_rule rbac_label_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_label_rule_tenant_isolation ON askcontent.askcontent_rbac_label_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_rbac_policy_version rbac_policy_version_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_policy_version_tenant_isolation ON askcontent.askcontent_rbac_policy_version USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_rbac_role_member rbac_role_member_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_role_member_tenant_isolation ON askcontent.askcontent_rbac_role_member USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_rbac_role rbac_role_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_role_tenant_isolation ON askcontent.askcontent_rbac_role USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_retrieval_plan retrieval_plan_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY retrieval_plan_tenant_isolation ON askcontent.askcontent_retrieval_plan USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_retrieval_run retrieval_run_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY retrieval_run_tenant_isolation ON askcontent.askcontent_retrieval_run USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_scope_change scope_change_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY scope_change_tenant_isolation ON askcontent.askcontent_scope_change USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_thread thread_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY thread_tenant_isolation ON askcontent.askcontent_thread USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_upload upload_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY upload_tenant_isolation ON askcontent.askcontent_upload USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_url_paste url_paste_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY url_paste_tenant_isolation ON askcontent.askcontent_url_paste USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: askcontent_workspace workspace_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY workspace_tenant_isolation ON askcontent.askcontent_workspace USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- PostgreSQL database dump complete
--

\unrestrict iP4Z16zN1ABAY3bYYZinhgMoTsr0Sntbxil1eJd0HPHigHAjBh2bBG6NIGIUS3H

