-- The shape of an askcontent tenant database.
--
-- Generated by tools/dump_sql.py from a migrated database, not from
-- the ORM: this is what the migrations actually produced, and where
-- that differs from what the models say, this is the one answering
-- queries.
--
-- Load first, then sql/data.sql.

--
-- PostgreSQL database dump
--

\restrict m66fdwBQSMtWIwjFhW7O8OUrFqpr8WMnX9GWQhse3xt4QVqg2A0g83YXHsf02AB

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: askcontent; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA askcontent;


--
-- Name: current_org(); Type: FUNCTION; Schema: askcontent; Owner: -
--

CREATE FUNCTION askcontent.current_org() RETURNS uuid
    LANGUAGE sql STABLE
    AS $$
  SELECT nullif(current_setting('askcontent.org_id', true), '')::uuid;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: answer_feedback; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.answer_feedback (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid,
    thread_id uuid,
    turn_id uuid,
    question text NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    citations jsonb DEFAULT '[]'::jsonb NOT NULL,
    verdict character varying(16) NOT NULL,
    reason character varying(32),
    comment text,
    promoted_case_id uuid,
    actor character varying(200),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.answer_feedback FORCE ROW LEVEL SECURITY;


--
-- Name: app_user; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.app_user (
    email character varying(320) NOT NULL,
    display_name character varying(200),
    password_hash text,
    is_active boolean DEFAULT true NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: askcontent_alembic_version; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.askcontent_alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: auth_session; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.auth_session (
    token_hash character varying(128) NOT NULL,
    user_id uuid NOT NULL,
    org_id uuid,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: authority_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.authority_rule (
    connector_id uuid NOT NULL,
    ordinal integer DEFAULT 0 NOT NULL,
    space character varying(200),
    path_prefix text,
    label character varying(200),
    tier character varying(16) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.authority_rule FORCE ROW LEVEL SECURITY;


--
-- Name: chat_thread; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.chat_thread (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid,
    title character varying(300),
    role character varying(120),
    created_by character varying(200),
    archived_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.chat_thread FORCE ROW LEVEL SECURITY;


--
-- Name: chat_turn; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.chat_turn (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    thread_id uuid NOT NULL,
    ordinal integer NOT NULL,
    question text NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    steps jsonb DEFAULT '[]'::jsonb NOT NULL,
    grounded boolean DEFAULT false NOT NULL,
    unsupported_reason text,
    answered_by jsonb DEFAULT '{}'::jsonb NOT NULL,
    elapsed_ms integer,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.chat_turn FORCE ROW LEVEL SECURITY;


--
-- Name: collection; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.collection (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(300) NOT NULL,
    description text,
    business_group character varying(200),
    state character varying(16) DEFAULT 'draft'::character varying NOT NULL,
    auto_accept_enumerable boolean DEFAULT true NOT NULL,
    materialised_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.collection FORCE ROW LEVEL SECURITY;


--
-- Name: collection_member; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.collection_member (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    kb_id character varying(200),
    title text,
    url text,
    contributed_by text[] DEFAULT '{}'::text[] NOT NULL,
    resolved_via character varying(16),
    resolve_score double precision,
    state character varying(16) DEFAULT 'member'::character varying NOT NULL,
    pinned character varying(8),
    pinned_by character varying(320),
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    missing_since timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    description text,
    space character varying(200),
    path text,
    doc_type character varying(32),
    owner character varying(320),
    source_created_at timestamp with time zone,
    source_updated_at timestamp with time zone,
    created_source character varying(16) DEFAULT 'none'::character varying NOT NULL,
    updated_source character varying(16) DEFAULT 'none'::character varying NOT NULL,
    date_evidence text,
    content_hash character varying(64),
    last_checked_at timestamp with time zone,
    last_changed_at timestamp with time zone,
    structure_hash character varying(64),
    last_verdict character varying(16),
    last_similarity double precision
);

ALTER TABLE ONLY askcontent.collection_member FORCE ROW LEVEL SECURITY;


--
-- Name: collection_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.collection_rule (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid NOT NULL,
    ordinal integer DEFAULT 0 NOT NULL,
    kind character varying(32) NOT NULL,
    effect character varying(8) DEFAULT 'include'::character varying NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    enumerable boolean DEFAULT true NOT NULL,
    last_run_at timestamp with time zone,
    last_candidate_count integer,
    capped boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.collection_rule FORCE ROW LEVEL SECURITY;


--
-- Name: connector; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.connector (
    slug character varying(64) NOT NULL,
    name character varying(300) NOT NULL,
    workspace_id uuid NOT NULL,
    knowledgebase_id uuid NOT NULL,
    state character varying(16) DEFAULT 'draft'::character varying NOT NULL,
    scope jsonb NOT NULL,
    scope_hash character varying(64) NOT NULL,
    sensitivity_ceiling character varying(16) DEFAULT 'internal'::character varying NOT NULL,
    access_groups text[] DEFAULT '{}'::text[] NOT NULL,
    declared_access_class character varying(200),
    retrieval_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    catalog_version integer DEFAULT 1 NOT NULL,
    policy_version integer DEFAULT 1 NOT NULL,
    credential_ciphertext bytea,
    credential_key_id character varying(64),
    last_ingest_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    collection_id uuid,
    description text DEFAULT ''::text NOT NULL,
    system_instructions text DEFAULT ''::text NOT NULL,
    CONSTRAINT ck_connector_state CHECK (((state)::text = ANY ((ARRAY['draft'::character varying, 'active'::character varying, 'suspended'::character varying])::text[])))
);

ALTER TABLE ONLY askcontent.connector FORCE ROW LEVEL SECURITY;


--
-- Name: document; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.document (
    connector_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    title text NOT NULL,
    url text NOT NULL,
    path text,
    space character varying(200),
    owner character varying(320),
    labels text[] DEFAULT '{}'::text[] NOT NULL,
    source_version character varying(200),
    source_updated_at timestamp with time zone,
    sensitivity character varying(16) DEFAULT 'internal'::character varying NOT NULL,
    acl_principals text[] DEFAULT '{}'::text[] NOT NULL,
    extras jsonb DEFAULT '{}'::jsonb NOT NULL,
    mime character varying(128),
    size_bytes bigint,
    file_hash character varying(64),
    text_hash character varying(64),
    parser_id character varying(64),
    parser_version character varying(32),
    parse_path character varying(32),
    parse_quality jsonb DEFAULT '{}'::jsonb NOT NULL,
    refusal_reason text,
    doc_type character varying(32),
    doc_type_confidence double precision,
    doc_type_source character varying(16),
    doc_type_evidence text[] DEFAULT '{}'::text[] NOT NULL,
    authority character varying(16) DEFAULT 'supporting'::character varying NOT NULL,
    authority_reason character varying(64),
    staleness character varying(16) DEFAULT 'unknown_age'::character varying NOT NULL,
    in_scope boolean DEFAULT true NOT NULL,
    exclusion_rule character varying(64),
    exclusion_detail text,
    quarantined boolean DEFAULT false NOT NULL,
    superseded_by character varying(300),
    canonical_doc_id character varying(300),
    missing_since timestamp with time zone,
    last_seen_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    content_hash character varying(64),
    structure_hash character varying(64),
    last_content_change_at timestamp with time zone,
    last_cosmetic_change_at timestamp with time zone
);

ALTER TABLE ONLY askcontent.document FORCE ROW LEVEL SECURITY;


--
-- Name: document_chunk; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.document_chunk (
    connector_id uuid NOT NULL,
    document_id uuid NOT NULL,
    chunk_id character varying(64) NOT NULL,
    ordinal integer NOT NULL,
    text text NOT NULL,
    heading_path text[] DEFAULT '{}'::text[] NOT NULL,
    parent_text text,
    page integer,
    is_table boolean DEFAULT false NOT NULL,
    token_estimate integer,
    chunker_version character varying(32) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_code boolean DEFAULT false NOT NULL,
    overlap text DEFAULT ''::text NOT NULL
);

ALTER TABLE ONLY askcontent.document_chunk FORCE ROW LEVEL SECURITY;


--
-- Name: document_pin; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.document_pin (
    connector_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    field character varying(32) NOT NULL,
    value text NOT NULL,
    actor character varying(320) NOT NULL,
    note text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.document_pin FORCE ROW LEVEL SECURITY;


--
-- Name: embed; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.embed (
    connector_id uuid NOT NULL,
    name character varying(200) NOT NULL,
    publishable_key character varying(128) NOT NULL,
    allowed_origins text[] DEFAULT '{}'::text[] NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    appearance jsonb DEFAULT '{}'::jsonb NOT NULL,
    session_count integer DEFAULT 0 NOT NULL,
    last_used_at timestamp with time zone
);

ALTER TABLE ONLY askcontent.embed FORCE ROW LEVEL SECURITY;


--
-- Name: embed_session; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.embed_session (
    embed_id uuid NOT NULL,
    visitor_id character varying(320) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.embed_session FORCE ROW LEVEL SECURITY;


--
-- Name: embedding; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.embedding (
    connector_id uuid NOT NULL,
    kind character varying(24) NOT NULL,
    ref_id character varying(300) NOT NULL,
    parent_ref character varying(300),
    content_hash character varying(64) NOT NULL,
    model_id character varying(200) NOT NULL,
    dimension integer NOT NULL,
    vector extensions.vector(1536) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.embedding FORCE ROW LEVEL SECURITY;


--
-- Name: eval_case; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.eval_case (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid NOT NULL,
    question text NOT NULL,
    expectations jsonb DEFAULT '[]'::jsonb NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    origin character varying(16) DEFAULT 'authored'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    role character varying(120),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.eval_case FORCE ROW LEVEL SECURITY;


--
-- Name: eval_result; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.eval_result (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    run_id uuid NOT NULL,
    case_id uuid,
    question text NOT NULL,
    passed boolean NOT NULL,
    failures jsonb DEFAULT '[]'::jsonb NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    cited jsonb DEFAULT '[]'::jsonb NOT NULL,
    grounded boolean DEFAULT false NOT NULL,
    elapsed_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.eval_result FORCE ROW LEVEL SECURITY;


--
-- Name: eval_run; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.eval_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    connector_id uuid NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    total integer DEFAULT 0 NOT NULL,
    passed integer DEFAULT 0 NOT NULL,
    failed integer DEFAULT 0 NOT NULL,
    context jsonb DEFAULT '{}'::jsonb NOT NULL
);

ALTER TABLE ONLY askcontent.eval_run FORCE ROW LEVEL SECURITY;


--
-- Name: field_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.field_rule (
    connector_id uuid NOT NULL,
    target character varying(64) NOT NULL,
    source character varying(200),
    coercion character varying(32) DEFAULT 'string'::character varying NOT NULL,
    value_map jsonb DEFAULT '{}'::jsonb NOT NULL,
    default_value text,
    prefer character varying(8) DEFAULT 'ecm'::character varying NOT NULL,
    observed_coverage double precision,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.field_rule FORCE ROW LEVEL SECURITY;


--
-- Name: glossary_term; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.glossary_term (
    connector_id uuid NOT NULL,
    term character varying(200) NOT NULL,
    definition text NOT NULL,
    aliases text[] DEFAULT '{}'::text[] NOT NULL,
    source character varying(32) DEFAULT 'human'::character varying NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    status character varying(16) DEFAULT 'confirmed'::character varying NOT NULL,
    method character varying(16) DEFAULT 'human'::character varying NOT NULL,
    confidence double precision,
    occurrences integer DEFAULT 0 NOT NULL,
    documents integer DEFAULT 0 NOT NULL,
    evidence text[] DEFAULT '{}'::text[] NOT NULL,
    reviewed_by character varying(320),
    reviewed_at timestamp with time zone
);

ALTER TABLE ONLY askcontent.glossary_term FORCE ROW LEVEL SECURITY;


--
-- Name: job; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.job (
    connector_id uuid,
    kind character varying(32) NOT NULL,
    status character varying(16) DEFAULT 'queued'::character varying NOT NULL,
    progress jsonb DEFAULT '{}'::jsonb NOT NULL,
    error text,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 3 NOT NULL,
    locked_at timestamp with time zone,
    locked_by character varying(120),
    run_after timestamp with time zone DEFAULT now() NOT NULL,
    collection_id uuid
);

ALTER TABLE ONLY askcontent.job FORCE ROW LEVEL SECURITY;


--
-- Name: knowledgebase; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.knowledgebase (
    kb_id character varying(200) NOT NULL,
    name character varying(300) NOT NULL,
    description text,
    document_count integer DEFAULT 0 NOT NULL,
    last_indexed_at timestamp with time zone,
    embedding_model character varying(200),
    embedding_dimension integer,
    exposes_acl boolean DEFAULT false NOT NULL,
    observed_fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.knowledgebase FORCE ROW LEVEL SECURITY;


--
-- Name: membership; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.membership (
    user_id uuid NOT NULL,
    role character varying(32) DEFAULT 'member'::character varying NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.membership FORCE ROW LEVEL SECURITY;


--
-- Name: message; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.message (
    thread_id uuid NOT NULL,
    role character varying(16) NOT NULL,
    text text DEFAULT ''::text NOT NULL,
    sidecar jsonb DEFAULT '{}'::jsonb NOT NULL,
    refused boolean DEFAULT false NOT NULL,
    refusal_reason text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.message FORCE ROW LEVEL SECURITY;


--
-- Name: org; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.org (
    slug character varying(64) NOT NULL,
    name character varying(200) NOT NULL,
    status character varying(24) DEFAULT 'active'::character varying NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: quarantine_item; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.quarantine_item (
    connector_id uuid NOT NULL,
    doc_id character varying(300) NOT NULL,
    matched_class character varying(64) NOT NULL,
    redacted_span text,
    status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
    reviewed_by character varying(320),
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.quarantine_item FORCE ROW LEVEL SECURITY;


--
-- Name: rbac_label_rule; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.rbac_label_rule (
    role_id uuid NOT NULL,
    space character varying(200),
    label character varying(200),
    effect character varying(8) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.rbac_label_rule FORCE ROW LEVEL SECURITY;


--
-- Name: rbac_policy_version; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.rbac_policy_version (
    connector_id uuid NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    changed_by character varying(320),
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.rbac_policy_version FORCE ROW LEVEL SECURITY;


--
-- Name: rbac_role; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.rbac_role (
    connector_id uuid NOT NULL,
    name character varying(120) NOT NULL,
    description text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.rbac_role FORCE ROW LEVEL SECURITY;


--
-- Name: rbac_role_member; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.rbac_role_member (
    role_id uuid NOT NULL,
    principal character varying(320) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.rbac_role_member FORCE ROW LEVEL SECURITY;


--
-- Name: retrieval_plan; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.retrieval_plan (
    connector_id uuid NOT NULL,
    question_hash character varying(64) NOT NULL,
    question text NOT NULL,
    plan_hash character varying(64) NOT NULL,
    spec jsonb NOT NULL,
    evidence_chunk_ids text[] DEFAULT '{}'::text[] NOT NULL,
    catalog_version integer NOT NULL,
    reranker_id character varying(64) NOT NULL,
    hit_count integer DEFAULT 0 NOT NULL,
    last_used_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.retrieval_plan FORCE ROW LEVEL SECURITY;


--
-- Name: retrieval_run; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.retrieval_run (
    connector_id uuid NOT NULL,
    actor character varying(320) NOT NULL,
    question text NOT NULL,
    spec jsonb NOT NULL,
    plan_hash character varying(64) NOT NULL,
    returned_doc_ids text[] DEFAULT '{}'::text[] NOT NULL,
    refused_doc_ids text[] DEFAULT '{}'::text[] NOT NULL,
    stale_index_count integer DEFAULT 0 NOT NULL,
    forbidden_count integer DEFAULT 0 NOT NULL,
    degraded text[] DEFAULT '{}'::text[] NOT NULL,
    answered boolean DEFAULT false NOT NULL,
    refusal_reason text,
    duration_ms double precision,
    cache_hit_rate double precision,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.retrieval_run FORCE ROW LEVEL SECURITY;


--
-- Name: scope_change; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.scope_change (
    connector_id uuid NOT NULL,
    actor character varying(320) NOT NULL,
    scope_before jsonb,
    scope_after jsonb NOT NULL,
    added integer DEFAULT 0 NOT NULL,
    removed integer DEFAULT 0 NOT NULL,
    unchanged integer DEFAULT 0 NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.scope_change FORCE ROW LEVEL SECURITY;


--
-- Name: thread; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.thread (
    workspace_id uuid NOT NULL,
    connector_id uuid NOT NULL,
    user_id uuid,
    title text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.thread FORCE ROW LEVEL SECURITY;


--
-- Name: upload; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.upload (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid,
    filename text NOT NULL,
    mime character varying(128) NOT NULL,
    size_bytes bigint NOT NULL,
    file_hash character varying(64) NOT NULL,
    text_hash character varying(64),
    parser_id character varying(64),
    parser_version character varying(32),
    parse_path character varying(32),
    parse_quality jsonb DEFAULT '{}'::jsonb NOT NULL,
    refusal_reason text,
    title text,
    blob bytea NOT NULL,
    accepted_reason character varying(32),
    accepted_by character varying(320),
    duplicate_of character varying(300),
    status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.upload FORCE ROW LEVEL SECURITY;


--
-- Name: url_paste; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.url_paste (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    collection_id uuid,
    url text NOT NULL,
    normalised text NOT NULL,
    outcome character varying(16) NOT NULL,
    matched_doc_id character varying(300),
    rung character varying(16),
    score double precision,
    detail text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.url_paste FORCE ROW LEVEL SECURITY;


--
-- Name: workspace; Type: TABLE; Schema: askcontent; Owner: -
--

CREATE TABLE askcontent.workspace (
    slug character varying(64) NOT NULL,
    name character varying(200) NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY askcontent.workspace FORCE ROW LEVEL SECURITY;


--
-- Name: answer_feedback answer_feedback_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.answer_feedback
    ADD CONSTRAINT answer_feedback_pkey PRIMARY KEY (id);


--
-- Name: askcontent_alembic_version askcontent_alembic_version_pkc; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.askcontent_alembic_version
    ADD CONSTRAINT askcontent_alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: chat_thread chat_thread_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.chat_thread
    ADD CONSTRAINT chat_thread_pkey PRIMARY KEY (id);


--
-- Name: chat_turn chat_turn_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.chat_turn
    ADD CONSTRAINT chat_turn_pkey PRIMARY KEY (id);


--
-- Name: chat_turn chat_turn_thread_id_ordinal_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.chat_turn
    ADD CONSTRAINT chat_turn_thread_id_ordinal_key UNIQUE (thread_id, ordinal);


--
-- Name: collection_member collection_member_collection_id_doc_id_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection_member
    ADD CONSTRAINT collection_member_collection_id_doc_id_key UNIQUE (collection_id, doc_id);


--
-- Name: collection_member collection_member_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection_member
    ADD CONSTRAINT collection_member_pkey PRIMARY KEY (id);


--
-- Name: collection collection_org_id_slug_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection
    ADD CONSTRAINT collection_org_id_slug_key UNIQUE (org_id, slug);


--
-- Name: collection collection_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection
    ADD CONSTRAINT collection_pkey PRIMARY KEY (id);


--
-- Name: collection_rule collection_rule_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection_rule
    ADD CONSTRAINT collection_rule_pkey PRIMARY KEY (id);


--
-- Name: eval_case eval_case_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_case
    ADD CONSTRAINT eval_case_pkey PRIMARY KEY (id);


--
-- Name: eval_result eval_result_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_result
    ADD CONSTRAINT eval_result_pkey PRIMARY KEY (id);


--
-- Name: eval_run eval_run_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_run
    ADD CONSTRAINT eval_run_pkey PRIMARY KEY (id);


--
-- Name: app_user pk_app_user; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.app_user
    ADD CONSTRAINT pk_app_user PRIMARY KEY (id);


--
-- Name: auth_session pk_auth_session; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.auth_session
    ADD CONSTRAINT pk_auth_session PRIMARY KEY (id);


--
-- Name: authority_rule pk_authority_rule; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.authority_rule
    ADD CONSTRAINT pk_authority_rule PRIMARY KEY (id);


--
-- Name: connector pk_connector; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.connector
    ADD CONSTRAINT pk_connector PRIMARY KEY (id);


--
-- Name: document pk_document; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document
    ADD CONSTRAINT pk_document PRIMARY KEY (id);


--
-- Name: document_chunk pk_document_chunk; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_chunk
    ADD CONSTRAINT pk_document_chunk PRIMARY KEY (id);


--
-- Name: document_pin pk_document_pin; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_pin
    ADD CONSTRAINT pk_document_pin PRIMARY KEY (id);


--
-- Name: embed pk_embed; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embed
    ADD CONSTRAINT pk_embed PRIMARY KEY (id);


--
-- Name: embed_session pk_embed_session; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embed_session
    ADD CONSTRAINT pk_embed_session PRIMARY KEY (id);


--
-- Name: embedding pk_embedding; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embedding
    ADD CONSTRAINT pk_embedding PRIMARY KEY (id);


--
-- Name: field_rule pk_field_rule; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.field_rule
    ADD CONSTRAINT pk_field_rule PRIMARY KEY (id);


--
-- Name: glossary_term pk_glossary_term; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.glossary_term
    ADD CONSTRAINT pk_glossary_term PRIMARY KEY (id);


--
-- Name: job pk_job; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.job
    ADD CONSTRAINT pk_job PRIMARY KEY (id);


--
-- Name: knowledgebase pk_knowledgebase; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.knowledgebase
    ADD CONSTRAINT pk_knowledgebase PRIMARY KEY (id);


--
-- Name: membership pk_membership; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.membership
    ADD CONSTRAINT pk_membership PRIMARY KEY (id);


--
-- Name: message pk_message; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.message
    ADD CONSTRAINT pk_message PRIMARY KEY (id);


--
-- Name: org pk_org; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.org
    ADD CONSTRAINT pk_org PRIMARY KEY (id);


--
-- Name: quarantine_item pk_quarantine_item; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.quarantine_item
    ADD CONSTRAINT pk_quarantine_item PRIMARY KEY (id);


--
-- Name: rbac_label_rule pk_rbac_label_rule; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_label_rule
    ADD CONSTRAINT pk_rbac_label_rule PRIMARY KEY (id);


--
-- Name: rbac_policy_version pk_rbac_policy_version; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_policy_version
    ADD CONSTRAINT pk_rbac_policy_version PRIMARY KEY (id);


--
-- Name: rbac_role pk_rbac_role; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role
    ADD CONSTRAINT pk_rbac_role PRIMARY KEY (id);


--
-- Name: rbac_role_member pk_rbac_role_member; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role_member
    ADD CONSTRAINT pk_rbac_role_member PRIMARY KEY (id);


--
-- Name: retrieval_plan pk_retrieval_plan; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.retrieval_plan
    ADD CONSTRAINT pk_retrieval_plan PRIMARY KEY (id);


--
-- Name: retrieval_run pk_retrieval_run; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.retrieval_run
    ADD CONSTRAINT pk_retrieval_run PRIMARY KEY (id);


--
-- Name: scope_change pk_scope_change; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.scope_change
    ADD CONSTRAINT pk_scope_change PRIMARY KEY (id);


--
-- Name: thread pk_thread; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.thread
    ADD CONSTRAINT pk_thread PRIMARY KEY (id);


--
-- Name: workspace pk_workspace; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.workspace
    ADD CONSTRAINT pk_workspace PRIMARY KEY (id);


--
-- Name: upload upload_org_id_file_hash_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.upload
    ADD CONSTRAINT upload_org_id_file_hash_key UNIQUE (org_id, file_hash);


--
-- Name: upload upload_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.upload
    ADD CONSTRAINT upload_pkey PRIMARY KEY (id);


--
-- Name: app_user uq_app_user_email; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.app_user
    ADD CONSTRAINT uq_app_user_email UNIQUE (email);


--
-- Name: auth_session uq_auth_session_token_hash; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.auth_session
    ADD CONSTRAINT uq_auth_session_token_hash UNIQUE (token_hash);


--
-- Name: connector uq_connector_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.connector
    ADD CONSTRAINT uq_connector_org_id UNIQUE (org_id, slug);


--
-- Name: document_chunk uq_document_chunk_document_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_chunk
    ADD CONSTRAINT uq_document_chunk_document_id UNIQUE (document_id, ordinal);


--
-- Name: document uq_document_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document
    ADD CONSTRAINT uq_document_connector_id UNIQUE (connector_id, doc_id);


--
-- Name: document_pin uq_document_pin_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_pin
    ADD CONSTRAINT uq_document_pin_connector_id UNIQUE (connector_id, doc_id, field);


--
-- Name: embed uq_embed_publishable_key; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embed
    ADD CONSTRAINT uq_embed_publishable_key UNIQUE (publishable_key);


--
-- Name: embedding uq_embedding_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embedding
    ADD CONSTRAINT uq_embedding_connector_id UNIQUE (connector_id, kind, ref_id, model_id);


--
-- Name: field_rule uq_field_rule_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.field_rule
    ADD CONSTRAINT uq_field_rule_connector_id UNIQUE (connector_id, target);


--
-- Name: glossary_term uq_glossary_term_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.glossary_term
    ADD CONSTRAINT uq_glossary_term_connector_id UNIQUE (connector_id, term);


--
-- Name: knowledgebase uq_knowledgebase_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.knowledgebase
    ADD CONSTRAINT uq_knowledgebase_org_id UNIQUE (org_id, kb_id);


--
-- Name: membership uq_membership_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.membership
    ADD CONSTRAINT uq_membership_org_id UNIQUE (org_id, user_id);


--
-- Name: org uq_org_slug; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.org
    ADD CONSTRAINT uq_org_slug UNIQUE (slug);


--
-- Name: rbac_role uq_rbac_role_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role
    ADD CONSTRAINT uq_rbac_role_connector_id UNIQUE (connector_id, name);


--
-- Name: rbac_role_member uq_rbac_role_member_role_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role_member
    ADD CONSTRAINT uq_rbac_role_member_role_id UNIQUE (role_id, principal);


--
-- Name: retrieval_plan uq_retrieval_plan_connector_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.retrieval_plan
    ADD CONSTRAINT uq_retrieval_plan_connector_id UNIQUE (connector_id, question_hash, catalog_version, reranker_id);


--
-- Name: workspace uq_workspace_org_id; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.workspace
    ADD CONSTRAINT uq_workspace_org_id UNIQUE (org_id, slug);


--
-- Name: url_paste url_paste_pkey; Type: CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.url_paste
    ADD CONSTRAINT url_paste_pkey PRIMARY KEY (id);


--
-- Name: ix_askcontent_authority_rule_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_authority_rule_org_id ON askcontent.authority_rule USING btree (org_id);


--
-- Name: ix_askcontent_connector_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_connector_org_id ON askcontent.connector USING btree (org_id);


--
-- Name: ix_askcontent_document_chunk_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_chunk_org_id ON askcontent.document_chunk USING btree (org_id);


--
-- Name: ix_askcontent_document_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_org_id ON askcontent.document USING btree (org_id);


--
-- Name: ix_askcontent_document_pin_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_document_pin_org_id ON askcontent.document_pin USING btree (org_id);


--
-- Name: ix_askcontent_embed_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embed_org_id ON askcontent.embed USING btree (org_id);


--
-- Name: ix_askcontent_embed_session_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embed_session_org_id ON askcontent.embed_session USING btree (org_id);


--
-- Name: ix_askcontent_embedding_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_embedding_org_id ON askcontent.embedding USING btree (org_id);


--
-- Name: ix_askcontent_field_rule_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_field_rule_org_id ON askcontent.field_rule USING btree (org_id);


--
-- Name: ix_askcontent_glossary_term_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_glossary_term_org_id ON askcontent.glossary_term USING btree (org_id);


--
-- Name: ix_askcontent_job_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_job_org_id ON askcontent.job USING btree (org_id);


--
-- Name: ix_askcontent_knowledgebase_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_knowledgebase_org_id ON askcontent.knowledgebase USING btree (org_id);


--
-- Name: ix_askcontent_membership_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_membership_org_id ON askcontent.membership USING btree (org_id);


--
-- Name: ix_askcontent_message_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_message_org_id ON askcontent.message USING btree (org_id);


--
-- Name: ix_askcontent_quarantine_item_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_quarantine_item_org_id ON askcontent.quarantine_item USING btree (org_id);


--
-- Name: ix_askcontent_rbac_label_rule_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_label_rule_org_id ON askcontent.rbac_label_rule USING btree (org_id);


--
-- Name: ix_askcontent_rbac_policy_version_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_policy_version_org_id ON askcontent.rbac_policy_version USING btree (org_id);


--
-- Name: ix_askcontent_rbac_role_member_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_role_member_org_id ON askcontent.rbac_role_member USING btree (org_id);


--
-- Name: ix_askcontent_rbac_role_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_rbac_role_org_id ON askcontent.rbac_role USING btree (org_id);


--
-- Name: ix_askcontent_retrieval_plan_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_retrieval_plan_org_id ON askcontent.retrieval_plan USING btree (org_id);


--
-- Name: ix_askcontent_retrieval_run_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_retrieval_run_org_id ON askcontent.retrieval_run USING btree (org_id);


--
-- Name: ix_askcontent_scope_change_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_scope_change_org_id ON askcontent.scope_change USING btree (org_id);


--
-- Name: ix_askcontent_thread_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_thread_org_id ON askcontent.thread USING btree (org_id);


--
-- Name: ix_askcontent_workspace_org_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_askcontent_workspace_org_id ON askcontent.workspace USING btree (org_id);


--
-- Name: ix_chat_thread_recent; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_chat_thread_recent ON askcontent.chat_thread USING btree (org_id, updated_at DESC) WHERE (archived_at IS NULL);


--
-- Name: ix_chunk_chunk_id; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_chunk_chunk_id ON askcontent.document_chunk USING btree (connector_id, chunk_id);


--
-- Name: ix_chunk_fts; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_chunk_fts ON askcontent.document_chunk USING gin (to_tsvector('english'::regconfig, text));


--
-- Name: ix_document_fts; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_document_fts ON askcontent.document USING gin (to_tsvector('english'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(path, ''::text))));


--
-- Name: ix_document_scope; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_document_scope ON askcontent.document USING btree (connector_id, in_scope);


--
-- Name: ix_document_space; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_document_space ON askcontent.document USING btree (connector_id, space);


--
-- Name: ix_document_updated; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_document_updated ON askcontent.document USING btree (connector_id, source_updated_at);


--
-- Name: ix_embedding_lookup; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_embedding_lookup ON askcontent.embedding USING btree (connector_id, kind);


--
-- Name: ix_embedding_vector_cosine; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_embedding_vector_cosine ON askcontent.embedding USING hnsw (vector extensions.vector_cosine_ops) WITH (m='16', ef_construction='64');


--
-- Name: ix_eval_result_run; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_eval_result_run ON askcontent.eval_result USING btree (run_id);


--
-- Name: ix_feedback_open; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_feedback_open ON askcontent.answer_feedback USING btree (connector_id, created_at DESC) WHERE (((verdict)::text = 'unhelpful'::text) AND (promoted_case_id IS NULL));


--
-- Name: ix_glossary_status; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_glossary_status ON askcontent.glossary_term USING btree (connector_id, status);


--
-- Name: ix_job_claimable; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_job_claimable ON askcontent.job USING btree (status, run_after) WHERE ((status)::text = ANY ((ARRAY['queued'::character varying, 'retry'::character varying])::text[]));


--
-- Name: ix_job_queue; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_job_queue ON askcontent.job USING btree (status, created_at);


--
-- Name: ix_member_checked; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_member_checked ON askcontent.collection_member USING btree (collection_id, last_checked_at NULLS FIRST);


--
-- Name: ix_member_state; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_member_state ON askcontent.collection_member USING btree (collection_id, state);


--
-- Name: ix_message_thread; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_message_thread ON askcontent.message USING btree (thread_id, created_at);


--
-- Name: ix_run_connector_time; Type: INDEX; Schema: askcontent; Owner: -
--

CREATE INDEX ix_run_connector_time ON askcontent.retrieval_run USING btree (connector_id, created_at);


--
-- Name: answer_feedback answer_feedback_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.answer_feedback
    ADD CONSTRAINT answer_feedback_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE SET NULL;


--
-- Name: answer_feedback answer_feedback_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.answer_feedback
    ADD CONSTRAINT answer_feedback_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: answer_feedback answer_feedback_thread_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.answer_feedback
    ADD CONSTRAINT answer_feedback_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES askcontent.chat_thread(id) ON DELETE SET NULL;


--
-- Name: answer_feedback answer_feedback_turn_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.answer_feedback
    ADD CONSTRAINT answer_feedback_turn_id_fkey FOREIGN KEY (turn_id) REFERENCES askcontent.chat_turn(id) ON DELETE SET NULL;


--
-- Name: chat_thread chat_thread_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.chat_thread
    ADD CONSTRAINT chat_thread_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE SET NULL;


--
-- Name: chat_thread chat_thread_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.chat_thread
    ADD CONSTRAINT chat_thread_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: chat_turn chat_turn_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.chat_turn
    ADD CONSTRAINT chat_turn_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: chat_turn chat_turn_thread_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.chat_turn
    ADD CONSTRAINT chat_turn_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES askcontent.chat_thread(id) ON DELETE CASCADE;


--
-- Name: collection_member collection_member_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection_member
    ADD CONSTRAINT collection_member_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.collection(id) ON DELETE CASCADE;


--
-- Name: collection_member collection_member_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection_member
    ADD CONSTRAINT collection_member_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: collection collection_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection
    ADD CONSTRAINT collection_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: collection_rule collection_rule_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection_rule
    ADD CONSTRAINT collection_rule_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.collection(id) ON DELETE CASCADE;


--
-- Name: collection_rule collection_rule_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.collection_rule
    ADD CONSTRAINT collection_rule_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: connector connector_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.connector
    ADD CONSTRAINT connector_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.collection(id);


--
-- Name: eval_case eval_case_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_case
    ADD CONSTRAINT eval_case_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: eval_case eval_case_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_case
    ADD CONSTRAINT eval_case_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: eval_result eval_result_case_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_result
    ADD CONSTRAINT eval_result_case_id_fkey FOREIGN KEY (case_id) REFERENCES askcontent.eval_case(id) ON DELETE SET NULL;


--
-- Name: eval_result eval_result_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_result
    ADD CONSTRAINT eval_result_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: eval_result eval_result_run_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_result
    ADD CONSTRAINT eval_result_run_id_fkey FOREIGN KEY (run_id) REFERENCES askcontent.eval_run(id) ON DELETE CASCADE;


--
-- Name: eval_run eval_run_connector_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_run
    ADD CONSTRAINT eval_run_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: eval_run eval_run_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.eval_run
    ADD CONSTRAINT eval_run_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: auth_session fk_auth_session_user_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.auth_session
    ADD CONSTRAINT fk_auth_session_user_id FOREIGN KEY (user_id) REFERENCES askcontent.app_user(id) ON DELETE CASCADE;


--
-- Name: authority_rule fk_authority_rule_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.authority_rule
    ADD CONSTRAINT fk_authority_rule_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: authority_rule fk_authority_rule_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.authority_rule
    ADD CONSTRAINT fk_authority_rule_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: connector fk_connector_knowledgebase_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.connector
    ADD CONSTRAINT fk_connector_knowledgebase_id FOREIGN KEY (knowledgebase_id) REFERENCES askcontent.knowledgebase(id) ON DELETE RESTRICT;


--
-- Name: connector fk_connector_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.connector
    ADD CONSTRAINT fk_connector_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: connector fk_connector_workspace_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.connector
    ADD CONSTRAINT fk_connector_workspace_id FOREIGN KEY (workspace_id) REFERENCES askcontent.workspace(id) ON DELETE CASCADE;


--
-- Name: document_chunk fk_document_chunk_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_chunk
    ADD CONSTRAINT fk_document_chunk_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: document_chunk fk_document_chunk_document_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_chunk
    ADD CONSTRAINT fk_document_chunk_document_id FOREIGN KEY (document_id) REFERENCES askcontent.document(id) ON DELETE CASCADE;


--
-- Name: document_chunk fk_document_chunk_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_chunk
    ADD CONSTRAINT fk_document_chunk_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: document fk_document_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document
    ADD CONSTRAINT fk_document_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: document fk_document_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document
    ADD CONSTRAINT fk_document_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: document_pin fk_document_pin_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_pin
    ADD CONSTRAINT fk_document_pin_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: document_pin fk_document_pin_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.document_pin
    ADD CONSTRAINT fk_document_pin_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: embed fk_embed_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embed
    ADD CONSTRAINT fk_embed_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: embed fk_embed_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embed
    ADD CONSTRAINT fk_embed_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: embed_session fk_embed_session_embed_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embed_session
    ADD CONSTRAINT fk_embed_session_embed_id FOREIGN KEY (embed_id) REFERENCES askcontent.embed(id) ON DELETE CASCADE;


--
-- Name: embed_session fk_embed_session_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embed_session
    ADD CONSTRAINT fk_embed_session_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: embedding fk_embedding_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embedding
    ADD CONSTRAINT fk_embedding_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: embedding fk_embedding_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.embedding
    ADD CONSTRAINT fk_embedding_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: field_rule fk_field_rule_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.field_rule
    ADD CONSTRAINT fk_field_rule_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: field_rule fk_field_rule_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.field_rule
    ADD CONSTRAINT fk_field_rule_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: glossary_term fk_glossary_term_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.glossary_term
    ADD CONSTRAINT fk_glossary_term_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: glossary_term fk_glossary_term_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.glossary_term
    ADD CONSTRAINT fk_glossary_term_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: job fk_job_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.job
    ADD CONSTRAINT fk_job_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: job fk_job_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.job
    ADD CONSTRAINT fk_job_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: knowledgebase fk_knowledgebase_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.knowledgebase
    ADD CONSTRAINT fk_knowledgebase_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: membership fk_membership_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.membership
    ADD CONSTRAINT fk_membership_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: membership fk_membership_user_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.membership
    ADD CONSTRAINT fk_membership_user_id FOREIGN KEY (user_id) REFERENCES askcontent.app_user(id) ON DELETE CASCADE;


--
-- Name: message fk_message_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.message
    ADD CONSTRAINT fk_message_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: message fk_message_thread_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.message
    ADD CONSTRAINT fk_message_thread_id FOREIGN KEY (thread_id) REFERENCES askcontent.thread(id) ON DELETE CASCADE;


--
-- Name: quarantine_item fk_quarantine_item_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.quarantine_item
    ADD CONSTRAINT fk_quarantine_item_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: quarantine_item fk_quarantine_item_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.quarantine_item
    ADD CONSTRAINT fk_quarantine_item_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: rbac_label_rule fk_rbac_label_rule_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_label_rule
    ADD CONSTRAINT fk_rbac_label_rule_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: rbac_label_rule fk_rbac_label_rule_role_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_label_rule
    ADD CONSTRAINT fk_rbac_label_rule_role_id FOREIGN KEY (role_id) REFERENCES askcontent.rbac_role(id) ON DELETE CASCADE;


--
-- Name: rbac_policy_version fk_rbac_policy_version_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_policy_version
    ADD CONSTRAINT fk_rbac_policy_version_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: rbac_policy_version fk_rbac_policy_version_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_policy_version
    ADD CONSTRAINT fk_rbac_policy_version_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: rbac_role fk_rbac_role_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role
    ADD CONSTRAINT fk_rbac_role_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: rbac_role_member fk_rbac_role_member_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role_member
    ADD CONSTRAINT fk_rbac_role_member_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: rbac_role_member fk_rbac_role_member_role_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role_member
    ADD CONSTRAINT fk_rbac_role_member_role_id FOREIGN KEY (role_id) REFERENCES askcontent.rbac_role(id) ON DELETE CASCADE;


--
-- Name: rbac_role fk_rbac_role_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.rbac_role
    ADD CONSTRAINT fk_rbac_role_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: retrieval_plan fk_retrieval_plan_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.retrieval_plan
    ADD CONSTRAINT fk_retrieval_plan_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: retrieval_plan fk_retrieval_plan_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.retrieval_plan
    ADD CONSTRAINT fk_retrieval_plan_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: retrieval_run fk_retrieval_run_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.retrieval_run
    ADD CONSTRAINT fk_retrieval_run_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: retrieval_run fk_retrieval_run_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.retrieval_run
    ADD CONSTRAINT fk_retrieval_run_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: scope_change fk_scope_change_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.scope_change
    ADD CONSTRAINT fk_scope_change_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: scope_change fk_scope_change_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.scope_change
    ADD CONSTRAINT fk_scope_change_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: thread fk_thread_connector_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.thread
    ADD CONSTRAINT fk_thread_connector_id FOREIGN KEY (connector_id) REFERENCES askcontent.connector(id) ON DELETE CASCADE;


--
-- Name: thread fk_thread_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.thread
    ADD CONSTRAINT fk_thread_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: thread fk_thread_user_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.thread
    ADD CONSTRAINT fk_thread_user_id FOREIGN KEY (user_id) REFERENCES askcontent.app_user(id) ON DELETE SET NULL;


--
-- Name: thread fk_thread_workspace_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.thread
    ADD CONSTRAINT fk_thread_workspace_id FOREIGN KEY (workspace_id) REFERENCES askcontent.workspace(id) ON DELETE CASCADE;


--
-- Name: workspace fk_workspace_org_id; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.workspace
    ADD CONSTRAINT fk_workspace_org_id FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: job job_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.job
    ADD CONSTRAINT job_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.collection(id) ON DELETE CASCADE;


--
-- Name: upload upload_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.upload
    ADD CONSTRAINT upload_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.collection(id) ON DELETE CASCADE;


--
-- Name: upload upload_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.upload
    ADD CONSTRAINT upload_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: url_paste url_paste_collection_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.url_paste
    ADD CONSTRAINT url_paste_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES askcontent.collection(id) ON DELETE CASCADE;


--
-- Name: url_paste url_paste_org_id_fkey; Type: FK CONSTRAINT; Schema: askcontent; Owner: -
--

ALTER TABLE ONLY askcontent.url_paste
    ADD CONSTRAINT url_paste_org_id_fkey FOREIGN KEY (org_id) REFERENCES askcontent.org(id) ON DELETE CASCADE;


--
-- Name: answer_feedback; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.answer_feedback ENABLE ROW LEVEL SECURITY;

--
-- Name: answer_feedback answer_feedback_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY answer_feedback_tenant_isolation ON askcontent.answer_feedback USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: authority_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.authority_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: authority_rule authority_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY authority_rule_tenant_isolation ON askcontent.authority_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: chat_thread; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.chat_thread ENABLE ROW LEVEL SECURITY;

--
-- Name: chat_thread chat_thread_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY chat_thread_tenant_isolation ON askcontent.chat_thread USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: chat_turn; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.chat_turn ENABLE ROW LEVEL SECURITY;

--
-- Name: chat_turn chat_turn_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY chat_turn_tenant_isolation ON askcontent.chat_turn USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: collection; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.collection ENABLE ROW LEVEL SECURITY;

--
-- Name: collection_member; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.collection_member ENABLE ROW LEVEL SECURITY;

--
-- Name: collection_member collection_member_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY collection_member_tenant_isolation ON askcontent.collection_member USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: collection_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.collection_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: collection_rule collection_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY collection_rule_tenant_isolation ON askcontent.collection_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: collection collection_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY collection_tenant_isolation ON askcontent.collection USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: connector; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.connector ENABLE ROW LEVEL SECURITY;

--
-- Name: connector connector_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY connector_tenant_isolation ON askcontent.connector USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: document; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.document ENABLE ROW LEVEL SECURITY;

--
-- Name: document_chunk; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.document_chunk ENABLE ROW LEVEL SECURITY;

--
-- Name: document_chunk document_chunk_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY document_chunk_tenant_isolation ON askcontent.document_chunk USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: document_pin; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.document_pin ENABLE ROW LEVEL SECURITY;

--
-- Name: document_pin document_pin_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY document_pin_tenant_isolation ON askcontent.document_pin USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: document document_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY document_tenant_isolation ON askcontent.document USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: embed; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.embed ENABLE ROW LEVEL SECURITY;

--
-- Name: embed_session; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.embed_session ENABLE ROW LEVEL SECURITY;

--
-- Name: embed_session embed_session_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY embed_session_tenant_isolation ON askcontent.embed_session USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: embed embed_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY embed_tenant_isolation ON askcontent.embed USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: embedding; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.embedding ENABLE ROW LEVEL SECURITY;

--
-- Name: embedding embedding_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY embedding_tenant_isolation ON askcontent.embedding USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: eval_case; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.eval_case ENABLE ROW LEVEL SECURITY;

--
-- Name: eval_case eval_case_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY eval_case_tenant_isolation ON askcontent.eval_case USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: eval_result; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.eval_result ENABLE ROW LEVEL SECURITY;

--
-- Name: eval_result eval_result_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY eval_result_tenant_isolation ON askcontent.eval_result USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: eval_run; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.eval_run ENABLE ROW LEVEL SECURITY;

--
-- Name: eval_run eval_run_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY eval_run_tenant_isolation ON askcontent.eval_run USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: field_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.field_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: field_rule field_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY field_rule_tenant_isolation ON askcontent.field_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: glossary_term; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.glossary_term ENABLE ROW LEVEL SECURITY;

--
-- Name: glossary_term glossary_term_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY glossary_term_tenant_isolation ON askcontent.glossary_term USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: job; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.job ENABLE ROW LEVEL SECURITY;

--
-- Name: job job_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY job_tenant_isolation ON askcontent.job USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: knowledgebase; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.knowledgebase ENABLE ROW LEVEL SECURITY;

--
-- Name: knowledgebase knowledgebase_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY knowledgebase_tenant_isolation ON askcontent.knowledgebase USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: membership; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.membership ENABLE ROW LEVEL SECURITY;

--
-- Name: membership membership_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY membership_tenant_isolation ON askcontent.membership USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: message; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.message ENABLE ROW LEVEL SECURITY;

--
-- Name: message message_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY message_tenant_isolation ON askcontent.message USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: quarantine_item; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.quarantine_item ENABLE ROW LEVEL SECURITY;

--
-- Name: quarantine_item quarantine_item_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY quarantine_item_tenant_isolation ON askcontent.quarantine_item USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: rbac_label_rule; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.rbac_label_rule ENABLE ROW LEVEL SECURITY;

--
-- Name: rbac_label_rule rbac_label_rule_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_label_rule_tenant_isolation ON askcontent.rbac_label_rule USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: rbac_policy_version; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.rbac_policy_version ENABLE ROW LEVEL SECURITY;

--
-- Name: rbac_policy_version rbac_policy_version_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_policy_version_tenant_isolation ON askcontent.rbac_policy_version USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: rbac_role; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.rbac_role ENABLE ROW LEVEL SECURITY;

--
-- Name: rbac_role_member; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.rbac_role_member ENABLE ROW LEVEL SECURITY;

--
-- Name: rbac_role_member rbac_role_member_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_role_member_tenant_isolation ON askcontent.rbac_role_member USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: rbac_role rbac_role_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY rbac_role_tenant_isolation ON askcontent.rbac_role USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: retrieval_plan; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.retrieval_plan ENABLE ROW LEVEL SECURITY;

--
-- Name: retrieval_plan retrieval_plan_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY retrieval_plan_tenant_isolation ON askcontent.retrieval_plan USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: retrieval_run; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.retrieval_run ENABLE ROW LEVEL SECURITY;

--
-- Name: retrieval_run retrieval_run_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY retrieval_run_tenant_isolation ON askcontent.retrieval_run USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: scope_change; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.scope_change ENABLE ROW LEVEL SECURITY;

--
-- Name: scope_change scope_change_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY scope_change_tenant_isolation ON askcontent.scope_change USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: thread; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.thread ENABLE ROW LEVEL SECURITY;

--
-- Name: thread thread_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY thread_tenant_isolation ON askcontent.thread USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: upload; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.upload ENABLE ROW LEVEL SECURITY;

--
-- Name: upload upload_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY upload_tenant_isolation ON askcontent.upload USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: url_paste; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.url_paste ENABLE ROW LEVEL SECURITY;

--
-- Name: url_paste url_paste_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY url_paste_tenant_isolation ON askcontent.url_paste USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- Name: workspace; Type: ROW SECURITY; Schema: askcontent; Owner: -
--

ALTER TABLE askcontent.workspace ENABLE ROW LEVEL SECURITY;

--
-- Name: workspace workspace_tenant_isolation; Type: POLICY; Schema: askcontent; Owner: -
--

CREATE POLICY workspace_tenant_isolation ON askcontent.workspace USING ((org_id = askcontent.current_org())) WITH CHECK ((org_id = askcontent.current_org()));


--
-- PostgreSQL database dump complete
--

\unrestrict m66fdwBQSMtWIwjFhW7O8OUrFqpr8WMnX9GWQhse3xt4QVqg2A0g83YXHsf02AB

